### ISSUE TITLE
Access-Control-Allow-Origin errors in Miro app deploy

### ISSUE THREAD

**Issue by chrisbloom7** [tpftg/dice.io#16]
I deployed a clone of this repo to Heroku and set it up as a Miro app following [your instructions](https://github.com/tpftg/dice.io/blob/master/docs/miro.md). I was able to see the Dice.io icon in the bottom toolbar and clicking it would open the sidebar, but it wouldn't roll any dice. Looking in the inspection panel in Chrome I found an error:

> Access to fetch at 'https://miro.com/api/v1/users/1234567890' from origin 'https://my-dice-io-app.herokuapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The error tracked back to this line in https://github.com/tpftg/dice.io/blob/3822fa924f9c6194349971a85dbba1835b65d542/src/miro/plugin.js#L26

I was not able to find any info on a valid workaround for that, and [several posts](https://www.google.com/search?q=miro+cross+origin&oq=miro+cross+origin) on the Miro community boards said this wasn't currently possible. I'm not sure if using the apps oauth token in the `fetch` would make any difference. I did find reference to an [experimental SDK interface](https://community.miro.com/developer-platform-and-apis-57/how-to-retrieve-user-name-from-webplugin-4926?postid=20749#post20749) which works if you change that block to this instead, but not sure you want to rely on that while it's still a beta feature.

```
miro.onReady(() => {
  // Attempt to get current user name (dice roller nickname)
  miro.board.getInfo().then((boardInfo) => {
    // Attempt to get team account id (dice roller channel)
    miro.account.get().then((account) => {
      startApp(boardInfo.currentUserContext.user.name, 'miro' + account.id)
    })
    .catch(e => {
      console.log('[Dice Roller] Failed to get team account id', e)
    })
  })
  .catch(e => {
    console.log('[Dice Roller] Failed to get board info', e)
  })
})
```

**Comment by kslimani** [comment]
Thank you for the report @chrisbloom7 .  I will take a look ASAP and attempt to fix the issue.

**Comment by kslimani** [comment]
@chrisbloom7 i released a new version. Could you please confirm if it fix the issue ?

**Comment by chrisbloom7** [comment]
@kslimani thanks for taking a look at this! I pulled down a fresh fork of your project, added a simple Procfile `web: node ./bin/index.js -a 0.0.0.0 -p $PORT` for heroku and force-pushed up to my heroku app. Confirmed that things work as expected now in both Miro desktop app for OS X and Miro.com in Chrome for OS X. 💯

**Comment by kslimani** [comment]
@chrisbloom7 , not sure if you noticed, but there is also a simple [Heroku example](https://github.com/tpftg/diceio-heroku) you can clone to deploy on Heroku.
_(may be "cleaner" than clone this project)_.
